spring:
  datasource:
    url: jdbc:mysql://localhost:3306/topalumniglobal_db?serverTimezone=UTC
    username: root
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true